# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{racket}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Manoogian III", "Erik Michaels-Ober"]
  s.date = %q{2009-11-21}
  s.default_executable = %q{racket}
  s.description = %q{Listen to your app.}
  s.email = %q{jm3@jm3.net}
  s.executables = ["racket"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "bin/event_simulator",
     "bin/racket",
     "doc/rubysdl.rb",
     "install_dependencies.sh",
     "racket.gemspec",
     "sounds/bing-bong.wav",
     "sounds/notify_cardinal1.aiff",
     "sounds/notify_cardinal2.aiff",
     "sounds/notify_original.aiff",
     "sounds/notify_robin.aiff",
     "sounds/phasing-bendy-bells.wav",
     "sounds/savage.wav",
     "sounds/skwlechy.wav",
     "sounds/squeaks.wav",
     "sounds/tiny-bubbles.mp3",
     "sounds/winding-weird-loop.wav",
     "ssh.rb"
  ]
  s.homepage = %q{http://github.com/jm3/racket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Listen to your app.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

